=== lasjen/hvl-dat107-databaser-V2026/videoer/video-03/01-personer/b-xml-schema-no-namespace/personer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
      xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--
      xmlns="http://home.hvl.no/databaser"
      targetNamespace="http://home.hvl.no/databaser"
      elementFormDefault="qualified"
  -->

<!-- Type Definisjoner - Simple -->
  <xs:simpleType name="pnrType">
    <xs:restriction base="xs:int">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="fornavnType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="20" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="etternavnType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="50" />
    </xs:restriction>
  </xs:simpleType>

<!-- Type Definisjoner - Complex -->
  <xs:complexType name="personType">
    <xs:sequence>
      <xs:element name="pnr" type="pnrType" />
      <xs:element name="fornavn" type="fornavnType" />
      <xs:element name="etternavn" type="etternavnType" />
      <xs:element name="fodselsdato" type="xs:date" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="personerType">
    <xs:sequence>
      <xs:element type="personType" name="person" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

<!-- Element Definisjoner -->
  <xs:element name="personer" type="personerType" />

</xs:schema>

=== lasjen/hvl-dat107-databaser-V2026/videoer/video-03/01-personer/b-xml-schema-no-namespace/personer.xml
<?xml version="1.0" encoding="utf-8"?>
<personer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="personer.xsd">

    <person>
        <pnr>0</pnr>
        <etternavn>Nordmann</etternavn>
        <fornavn>IdaMedEtVeldigLangtFornavn</fornavn>
        <fodselsdato>1980-01-32</fodselsdato>
    </person>

    <person>
        <pnr>2</pnr>
        <fornavn>Kari</fornavn>
        <etternavn>Pettersen</etternavn>
        <fodselsdato>1993-08-23</fodselsdato>
    </person>

</personer>
