=== lasjen/hvl-dat107-databaser-V2026/videoer/video-03/02-birken/eks-01-generelt/birken-paamelding.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
   <xs:element name="person">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="id" type="xs:ID"/>
            <xs:element name="navn" type="xs:string"/>
            <xs:element name="fdato" type="xs:date"/>
            <xs:element name="medlem" type="xs:boolean"/>
            <xs:element name="poeng" type="xs:decimal"/>
            <xs:element name="hjemmeside" type="xs:anyURI"/>
            <xs:element name="pulje" type="xs:integer"/>
            <xs:element name="starttid" type="xs:dateTime"/>
            <xs:element name="foresattId" type="xs:IDREF" minOccurs="0"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="birken">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="person" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== lasjen/hvl-dat107-databaser-V2026/videoer/video-03-xml-&-xml-schema/birken-paamelding.xml
<?xml version="1.0" encoding="UTF-8"?>
<birken xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="birken-paamelding.xsd">

   <person>
      <!-- Foresatt -->
      <id>h1</id>
      <navn>Lasse Jenssen</navn>
      <fdato>1983-05-12</fdato>
      <medlem>true</medlem>
      <poeng>1200.01</poeng>
      <hjemmeside>https://www.jcon.no/blog</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T08:00:00</starttid>
   </person>

   <person>
      <!-- Foresatt -->
      <id>h1</id>
      <navn>Ola Hansen</navn>
      <fdato>1975-03-00</fdato>
      <medlem>nei</medlem>
      <poeng>1405.21</poeng>
      <hjemmeside>Kan være hva som helst</hjemmeside>
      <!-- <hjemmeside>https://www.olahansen.no</hjemmeside> -->
      <pulje>1.1</pulje>
      <starttid>2026-03-15</starttid>
      <!-- <starttid>2026-03-15T07:30:00</starttid> -->
   </person>

   <!-- Barn under 16 år -->
   <person>
      <id>d5</id>
      <navn>Karianne Blikra Jenssen</navn>
      <fdato>2012-12-02</fdato>
      <medlem>false</medlem>
      <poeng>621.23</poeng>
      <hjemmeside>https://www.blikra.no/karianne</hjemmeside>
      <pulje>5</pulje>
      <starttid>2026-03-15T09:15:00</starttid>
      <foresattId>h1</foresattId>
   </person>

   <!-- 20 nye herrer (h3-h22) -->
   <person>
      <id>h3</id>
      <navn>Jonas Berg</navn>
      <fdato>1988-01-14</fdato>
      <medlem>true</medlem>
      <poeng>980.12</poeng>
      <hjemmeside>https://example.com/jonas-berg</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T07:45:00</starttid>
   </person>
   <person>
      <id>h4</id>
      <navn>Mats Lunde</navn>
      <fdato>1990-04-21</fdato>
      <medlem>false</medlem>
      <poeng>765.33</poeng>
      <hjemmeside>https://example.com/mats-lunde</hjemmeside>
      <pulje>3</pulje>
      <starttid>2026-03-15T07:48:00</starttid>
   </person>
   <person>
      <id>h5</id>
      <navn>Thomas Engen</navn>
      <fdato>1988-05-03</fdato>
      <medlem>true</medlem>
      <poeng>905.20</poeng>
      <hjemmeside>https://example.com/thomas-engen</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T07:49:00</starttid>
   </person>
   <person>
      <id>h6</id>
      <navn>Henrik Aas</navn>
      <fdato>1982-11-05</fdato>
      <medlem>true</medlem>
      <poeng>1105.44</poeng>
      <hjemmeside>https://example.com/henrik-aas</hjemmeside>
      <pulje>1</pulje>
      <starttid>2026-03-15T07:50:00</starttid>
   </person>
   <person>
      <id>h7</id>
      <navn>Anders Lie</navn>
      <fdato>1979-09-18</fdato>
      <medlem>false</medlem>
      <poeng>845.67</poeng>
      <hjemmeside>https://example.com/anders-lie</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T07:52:00</starttid>
   </person>
   <person>
      <id>h8</id>
      <navn>Kristoffer Moe</navn>
      <fdato>1995-02-10</fdato>
      <medlem>true</medlem>
      <poeng>930.22</poeng>
      <hjemmeside>https://example.com/kristoffer-moe</hjemmeside>
      <pulje>4</pulje>
      <starttid>2026-03-15T07:55:00</starttid>
   </person>
   <person>
      <id>h9</id>
      <navn>Sindre Johansen</navn>
      <fdato>1986-07-29</fdato>
      <medlem>true</medlem>
      <poeng>1010.50</poeng>
      <hjemmeside>https://example.com/sindre-johansen</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T07:57:00</starttid>
   </person>
   <person>
      <id>h10</id>
      <navn>Emil Røed</navn>
      <fdato>1992-03-12</fdato>
      <medlem>false</medlem>
      <poeng>720.84</poeng>
      <hjemmeside>https://example.com/emil-rod</hjemmeside>
      <pulje>3</pulje>
      <starttid>2026-03-15T08:00:00</starttid>
   </person>
   <person>
      <id>h11</id>
      <navn>Vetle Skaar</navn>
      <fdato>1984-05-22</fdato>
      <medlem>true</medlem>
      <poeng>990.77</poeng>
      <hjemmeside>https://example.com/vetle-skaar</hjemmeside>
      <pulje>1</pulje>
      <starttid>2026-03-15T08:02:00</starttid>
   </person>
   <person>
      <id>h12</id>
      <navn>Trym Eide</navn>
      <fdato>1981-10-09</fdato>
      <medlem>false</medlem>
      <poeng>800.12</poeng>
      <hjemmeside>https://example.com/trym-eide</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T08:04:00</starttid>
   </person>
   <person>
      <id>h13</id>
      <navn>Leif Knutsen</navn>
      <fdato>1977-08-16</fdato>
      <medlem>true</medlem>
      <poeng>1055.66</poeng>
      <hjemmeside>https://example.com/leif-knutsen</hjemmeside>
      <pulje>1</pulje>
      <starttid>2026-03-15T08:06:00</starttid>
   </person>
   <person>
      <id>h14</id>
      <navn>Petter Dahl</navn>
      <fdato>1993-06-03</fdato>
      <medlem>false</medlem>
      <poeng>760.42</poeng>
      <hjemmeside>https://example.com/petter-dahl</hjemmeside>
      <pulje>3</pulje>
      <starttid>2026-03-15T08:08:00</starttid>
   </person>
   <person>
      <id>h15</id>
      <navn>Jørgen Hauge</navn>
      <fdato>1989-12-24</fdato>
      <medlem>true</medlem>
      <poeng>1005.90</poeng>
      <hjemmeside>https://example.com/jorgen-hauge</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T08:10:00</starttid>
   </person>
   <person>
      <id>h16</id>
      <navn>Eirik Tangen</navn>
      <fdato>1987-02-27</fdato>
      <medlem>false</medlem>
      <poeng>835.13</poeng>
      <hjemmeside>https://example.com/eirik-tangen</hjemmeside>
      <pulje>3</pulje>
      <starttid>2026-03-15T08:12:00</starttid>
   </person>
   <person>
      <id>h17</id>
      <navn>Sigurd Vik</navn>
      <fdato>1980-01-30</fdato>
      <medlem>true</medlem>
      <poeng>1120.88</poeng>
      <hjemmeside>https://example.com/sigurd-vik</hjemmeside>
      <pulje>1</pulje>
      <starttid>2026-03-15T08:14:00</starttid>
   </person>
   <person>
      <id>h18</id>
      <navn>Filip Nymoen</navn>
      <fdato>1996-09-11</fdato>
      <medlem>false</medlem>
      <poeng>745.25</poeng>
      <hjemmeside>https://example.com/filip-nymoen</hjemmeside>
      <pulje>4</pulje>
      <starttid>2026-03-15T08:16:00</starttid>
   </person>
   <person>
      <id>h19</id>
      <navn>Ulrik Foss</navn>
      <fdato>1978-04-07</fdato>
      <medlem>true</medlem>
      <poeng>990.31</poeng>
      <hjemmeside>https://example.com/ulrik-foss</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T08:18:00</starttid>
   </person>
   <person>
      <id>h20</id>
      <navn>Ruben Sand</navn>
      <fdato>1991-11-19</fdato>
      <medlem>false</medlem>
      <poeng>780.64</poeng>
      <hjemmeside>https://example.com/ruben-sand</hjemmeside>
      <pulje>3</pulje>
      <starttid>2026-03-15T08:20:00</starttid>
   </person>
   <person>
      <id>h21</id>
      <navn>Kristian Lund</navn>
      <fdato>1985-03-23</fdato>
      <medlem>true</medlem>
      <poeng>1025.47</poeng>
      <hjemmeside>https://example.com/kristian-lund</hjemmeside>
      <pulje>1</pulje>
      <starttid>2026-03-15T08:22:00</starttid>
   </person>
   <person>
      <id>h22</id>
      <navn>Kenneth Myhre</navn>
      <fdato>1983-07-02</fdato>
      <medlem>false</medlem>
      <poeng>850.76</poeng>
      <hjemmeside>https://example.com/kenneth-myhre</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T08:24:00</starttid>
   </person>

   <!-- 20 nye damer (d6-d25) -->
   <person>
      <id>d6</id>
      <navn>Marie Solberg</navn>
      <fdato>1994-02-08</fdato>
      <medlem>true</medlem>
      <poeng>970.33</poeng>
      <hjemmeside>https://example.com/marie-solberg</hjemmeside>
      <pulje>4</pulje>
      <starttid>2026-03-15T09:00:00</starttid>
   </person>
   <person>
      <id>d7</id>
      <navn>Silje Haug</navn>
      <fdato>1990-10-15</fdato>
      <medlem>false</medlem>
      <poeng>720.22</poeng>
      <hjemmeside>https://example.com/silje-haug</hjemmeside>
      <pulje>3</pulje>
      <starttid>2026-03-15T09:02:00</starttid>
   </person>
   <person>
      <id>d8</id>
      <navn>Line Karlsen</navn>
      <fdato>1988-06-19</fdato>
      <medlem>true</medlem>
      <poeng>990.55</poeng>
      <hjemmeside>https://example.com/line-karlsen</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T09:04:00</starttid>
   </person>
   <person>
      <id>d9</id>
      <navn>Nora Vik</navn>
      <fdato>1995-11-30</fdato>
      <medlem>false</medlem>
      <poeng>740.68</poeng>
      <hjemmeside>https://example.com/nora-vik</hjemmeside>
      <pulje>3</pulje>
      <starttid>2026-03-15T09:06:00</starttid>
   </person>
   <person>
      <id>d10</id>
      <navn>Tuva Nilsen</navn>
      <fdato>1992-01-05</fdato>
      <medlem>true</medlem>
      <poeng>950.10</poeng>
      <hjemmeside>https://example.com/tuva-nilsen</hjemmeside>
      <pulje>4</pulje>
      <starttid>2026-03-15T09:08:00</starttid>
   </person>
   <person>
      <id>d11</id>
      <navn>Camilla Andersen</navn>
      <fdato>1987-03-28</fdato>
      <medlem>false</medlem>
      <poeng>760.91</poeng>
      <hjemmeside>https://example.com/camilla-andersen</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T09:10:00</starttid>
   </person>
   <person>
      <id>d12</id>
      <navn>Ida Berg</navn>
      <fdato>1991-04-17</fdato>
      <medlem>true</medlem>
      <poeng>980.44</poeng>
      <hjemmeside>https://example.com/ida-berg</hjemmeside>
      <pulje>3</pulje>
      <starttid>2026-03-15T09:12:00</starttid>
   </person>
   <person>
      <id>d13</id>
      <navn>Emilie Larsen</navn>
      <fdato>1996-07-22</fdato>
      <medlem>false</medlem>
      <poeng>740.21</poeng>
      <hjemmeside>https://example.com/emilie-larsen</hjemmeside>
      <pulje>4</pulje>
      <starttid>2026-03-15T09:14:00</starttid>
   </person>
   <person>
      <id>d14</id>
      <navn>Ragnhild Myklebust</navn>
      <fdato>1983-08-11</fdato>
      <medlem>true</medlem>
      <poeng>1015.32</poeng>
      <hjemmeside>https://example.com/ragnhild-myklebust</hjemmeside>
      <pulje>2</pulje>
      <starttid>2026-03-15T09:16:00</starttid>
   </person>
   <person>
      <id>d15</id>
