=== lasjen/hvl-dat107-databaser-V2026/forelesninger/forelesning-01/01-personer/c-xml-schema-with-ns/personer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      targetNamespace="http://home.hvl.no/databaser"
      xmlns="http://home.hvl.no/databaser"
      xmlns:dat="http://home.hvl.no/databaser"
      elementFormDefault="qualified">

<!-- Type Definisjoner - Simple -->
    <xs:simpleType name="pnrType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fornavnType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern
                  value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Type Definisjoner - Complex -->
    <xs:complexType name="personerType">
        <xs:sequence>
            <xs:element name="person" type="personType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personType">
        <xs:sequence>
            <xs:element name="fornavn" type="fornavnType" />
            <xs:element name="etternavn" type="xs:string" />
            <xs:element name="barn" type="xs:integer" minOccurs="0"/>
            <xs:element name="fodselsdato" type="xs:date" />
            <xs:element name="email" type="emailType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="pnr" type="pnrType" use="required"/>
    </xs:complexType>

<!-- Element Definisjoner -->
<!-- XPath er namespace‑sensitiv.
     Derfor må vi prefikse element i xpath ustrykk med "dat:".  -->
    <xs:element name="personer" type="personerType">
        <xs:key name="pnrKey">
            <xs:selector xpath="dat:person"/>
            <xs:field xpath="@pnr"/>
        </xs:key>
        <xs:unique name="emailUnique">
            <xs:selector xpath="dat:person"/>
            <xs:field xpath="dat:email"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== lasjen/hvl-dat107-databaser-V2026/forelesninger/forelesning-01/01-personer/c-xml-schema-with-ns/personer.xml
<?xml version="1.0" encoding="utf-8"?>
<personer
      xmlns="http://home.hvl.no/databaser"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://home.hvl.no/databaser personer.xsd">

  <person pnr="1">
    <fornavn>Ola</fornavn>
    <etternavn>Nordmann</etternavn>
    <barn>1</barn>
    <fodselsdato>1980-01-01</fodselsdato>
    <email>enkel@example.com</email>
  </person>

  <person pnr="1">
    <fornavn>Kari</fornavn>
    <etternavn>Svenske</etternavn>
    <fodselsdato>1993-08-23</fodselsdato>
    <email>enkel@example.com</email>
  </person>

</personer>
