=== lasjen/hvl-dat107-databaser-V2026/eksamener/2025-jan/menu.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="http://eksamen.hvl.no/dat107"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <xs:element name="menu" type="menuType"/>

   <xs:complexType name="menuType">
      <xs:sequence>
         <xs:element name="starters" type="startersType" maxOccurs="1"/>
         <xs:element name="mainCourses" type="mainCoursesType" maxOccurs="1"/>
         <xs:element name="desserts" type="dessertsType" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="startersType">
      <xs:sequence>
         <xs:element name="starter" type="starterType" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="mainCoursesType">
      <xs:sequence>
         <xs:element name="mainCourse" type="mainCourseType" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="dessertsType">
      <xs:sequence>
         <xs:element name="dessert" type="dessertType" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="starterType">
      <xs:sequence>
         <xs:element name="description" type="xs:string"/>
         <xs:element name="price" type="xs:decimal"/>
         <xs:element name="allergens" type="allergensType" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
   </xs:complexType>

   <xs:complexType name="mainCourseType">
      <xs:sequence>
         <xs:element name="description" type="xs:string"/>
         <xs:element name="price" type="xs:decimal"/>
         <xs:element name="allergens" type="allergensType" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
   </xs:complexType>

   <xs:complexType name="dessertType">
      <xs:sequence>
         <xs:element name="description" type="xs:string"/>
         <xs:element name="price" type="xs:decimal"/>
         <xs:element name="allergens" type="allergensType" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
   </xs:complexType>

   <xs:complexType name="allergensType">
      <xs:sequence>
         <xs:element name="allergen" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== lasjen/hvl-dat107-databaser-V2026/eksamener/2025-jan/menu.xml
<?xml version="1.0" encoding="utf-8" ?>
<menu xmlns="http://eksamen.hvl.no/dat107"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://eksamen.hvl.no/dat107 menu.xsd">
    <starters>
        <starter name="Garlic Bread">
            <description>Garlic bread with cheese</description>
            <price>100.00</price>
        </starter>
        <starter name="Shrimp coctail">
            <description>Shrimp cocktail with avocado</description>
            <price>150.00</price>
        </starter>
    </starters>
    <mainCourses>
        <mainCourse name="Beef steak">
            <description>Beef steak with pepper sauce</description>
            <price>250.00</price>
            <allergens>
                <allergen>Gluten</allergen>
                <allergen>Laktose</allergen>
            </allergens>
        </mainCourse>
        <mainCourse name="Blab la bla">
            <description>Blaribla</description>
            <price>179.00</price>
        </mainCourse>
    </mainCourses>
    <desserts>
        <dessert name="Chocolate cake">
            <description>Chocolate cake with ice cream</description>
            <price>100.00</price>
        </dessert>
        <dessert name="Cheese cake">
            <description>Cheese cake duddli du</description>
            <price>110.00</price>
        </dessert>
    </desserts>
</menu>
